### ISSUE TITLE
User management for webdav-sync

### ISSUE THREAD

**Issue by moshere** [bermi/webdav-sync#19]
Hi,
We would like to implement user management for the webdav-sync.
It means that every user that login to the system will be able to browse to separate directories.
In addition to manage set of users.

Which component / tool / code we can use for this.

Thank you,
Moshe

**Comment by benredvan** [comment]
Not entirely sure what you mean. Sounds like you're asking about webdav server management.

I'm closing this issue as it's not an issue with the software.
