### ISSUE TITLE
a email like username will cause error

### ISSUE THREAD

**Issue by aulian** [bermi/webdav-sync#5]
a email like username (like bob@gmail.com) will cause error

``` bash
webdav-sync --local_base /var/src/code --remote_base "https://bob@gmail.com:pass@demandware.com/webdav/"
```

**Comment by bensmoif** [comment]
Dang, I thought we fixed this a few releases ago. I'll look into it and hopefully have it patched by weeks end! Thanks Aulian.

**Comment by aulian** [comment]
look forward your brillant work

**Comment by bensmoif** [comment]
In reviewing: to support this we'll have to add two new options for username and password distinct from --remote_path="https://username:passwd@really-long-and-ugly-login-string.com/webdavdrop/" 

I wish this was something we'd caught earlier in the dev process, it might require a major version change in the end to do it cleanly

**Comment by bensmoif** [comment]
@aulian: This is now fixed, and pretty cleanly. We now have --username and --password options for secure login that will accept any special characters. Please test and let me know if you have any issues with the new 0.4.4 release!
